### ISSUE TITLE
better handling of checkbox values

### ISSUE THREAD

**Issue by sheppard** [wq/wq.db#44]
The latest version of DRF handles boolean values more robustly, but it breaks some things with how checkboxes worked before (e.g. the `<input>` needs to have `value="t"` instead of just "on").  Also, unchecking a box on an existing record doesn't necessarily cause an update to `False` (since the field is omitted entirely).  Need a better way of handling checkbox values (here and/or in [wq.app](https://wq.io/wq.app)).

**Comment by tomaszn** [comment]
I suggested one quick solution in #69 - it can be treated as two `choices` (t / f) and be rendered as such by wq.app. Default labels could be set to ✓ and ✗ for international use.

**Comment by sheppard** [comment]
Closing in favor of #69.
