### ISSUE TITLE
no user profile information available in login.json

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.db#59]
One of the least intrusive ways to extend the Django's User model is to create a separate model with OneToOne relation to the User model, that contains additional fields about the user (e.g. the company he belongs to). 
It would be useful if the serializer could include that information at /login.json. 
One solution would be to provide a configuration option "EXPOSE_USER_PROFILE_CLASSES" and use it to add related OneToOne objects recursively (e.g. to access user.profile.company.name).

**Comment by sheppard** [comment]
There is a way to do this already, though it's not intuitive.  /login.json uses whatever serializer the router has registered for the `auth.User` model (the default is `wq.db.rest.auth.serializers.UserSerializer`).  There is a function for registering just the serializer for a model without actually listing it in the API (see https://github.com/wq/wq.db/blob/master/rest/auth/rest.py).  You can register the custom serializer in your own rest.py, and then it should work as long as your custom app is listed after `wq.db.rest.auth` in `INSTALLED_APPS`.

**Comment by tomaszn** [comment]
Thanks, it works. If someone else needed that: 

    # in my serializers.py
    class UserProfileSerializer(UserSerializer):
      def to_representation(self, instance):
        result = super(UserProfileSerializer, self).to_representation(instance)
        result['company_name'] = instance.profile.company.name
        return result

    # in my rest.py
    rest.router.register_serializer(User, UserProfileSerializer)
