### ISSUE TITLE
list_exclude causes fields to not show up in config

### ISSUE THREAD

**Issue by sheppard** [wq/wq.db#62]
Due to how the serializer interprets `is_detail` when running `get_wq_config()`

**Comment by sheppard** [comment]
One workaround is to overwrite `get_fields_for_config()` to restore missing fields:

```python
class MyModelSerializer(ModelSerializer)
    customfield = ExpensiveField()

    def get_fields_for_config(self):
        fields = super().get_fields_for_config()
        fields['customfield'] = ExpensiveField()
        return fields

   class Meta:
        list_exclude = ('customfield',)
```

**Comment by tomaszn** [comment]
Please note that the current behavior is useful to completely ignore `ManyToManyField`s, which otherwise need to be sent every time (e.g. list of all `Book`s when updating the `Author`).

**Comment by sheppard** [comment]
I fixed this, but also added a `config_exclude` option to make it easy to emulate the existing behavior:

```python
class CustomSerializer(ModelSerializer):
    class Meta:
        config_exclude = list_exclude = ['books']
```

**Comment by tomaszn** [comment]
This backwards incompatible change was released in v1.1.3 and affects projects using wq==v1.1.0 (which requires `wq.db>=1.1.0,<1.2.0`).

Is it possible to have wq v.1.1.2 released that would depend strictly on wq.db 1.1.2?

**Comment by sheppard** [comment]
Thanks for reporting this.  I think I would rather revert these changes, release wq.db 1.1.4, then restore the changes for wq.db 1.2.0.  It is my goal that wq.* releases more or less follow semver, which is one reason the top level wq package uses looser requirements.  In general, I intend to avoid backwards incompatible changes for patch releases, but obviously this is a case where that didn't happen.

On a related note, has wq.app==v1.1.2 caused any similar issues?

**Comment by tomaszn** [comment]
Thanks! Works for me.

As for wq.app, I'm using my forked version which supports batch requests. What I can say is that it's still compatible with wq.db :-)
