### ISSUE TITLE
result_inline.html character encoding issue

### ISSUE THREAD

**Issue by tubaman** [wq/wq.db#76]
When creating a campaign with a field name containing a single quote(ex: Child's Name), the rendered label in result_inline.html partial doesn't encode the quote properly(ex: Child&#x27;s Name).  However the description containing the same text renders correctly(ex: Child's Name).

**Comment by tubaman** [comment]
I think this might be a https://github.com/powered-by-wq/try.wq.io issue since I'm running that repo when encountering this.

**Comment by sheppard** [comment]
Yes, this is probably an issue with try.wq.io.  I created powered-by-wq/try.wq.io#21 for followup.
