### ISSUE TITLE
DRF 3.10 breaking change

### ISSUE THREAD

**Issue by tomaszn** [wq/wq.db#77]
On a fresh install of wq I get:
```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/da/lib/python3.6/site-packages/wq/db/rest/__init__.py", line 2, in <module>
    from .routers import ModelRouter, router
  File "/tmp/da/lib/python3.6/site-packages/wq/db/rest/routers.py", line 14, in <module>
    from .views import SimpleViewSet, ModelViewSet
  File "/tmp/da/lib/python3.6/site-packages/wq/db/rest/views.py", line 3, in <module>
    from rest_framework.decorators import detail_route
ImportError: cannot import name 'detail_route'
```
[DRF 3.9 deprecated detail_route](https://www.django-rest-framework.org/community/3.9-announcement/#action-decorator-replaces-list_route-and-detail_route
), and recently released DRF 3.10 removed it.

Let's add `<3.10` to the version specification (and include the fix in 1.1.4 we talked about):
https://github.com/wq/wq.db/blob/753fe40eb5f5a40ce64128c511d62c94116d2958/setup.py#L86

**Comment by sheppard** [comment]
Thanks, I [released 1.1.4](https://github.com/wq/wq.db/releases/tag/v1.1.4) and then updated the [build matrix](https://travis-ci.org/wq/wq.db) to include DRF 3.10.  I also added DRF 3.8 to the matrix since it is the lower bound.  If fixing 3.10 support breaks 3.8 support we can drop 3.8.
